---
controller:
  kind: Deployment
  hostNetwork: true
  replicaCount: 1

  hostPort:
    enabled: true
    http: 80
    https: 443

  service:
    type: ""

  admissionWebhooks:
    enabled: true

  ingressClassResource:
    name: public

  config:
    allowSnippetAnnotations: true
    annotations-risk-level: Critical
    log-format-upstream: 'remote_addr: $remote_addr host: $host remote_user: $remote_user time_local: [$time_local] request: $request status: $status body_bytes_sent: $body_bytes_sent http_referer: $http_referer http_user_agent: $http_user_agent request_length: $request_length request_time: $request_time proxy_upstream_name: [$proxy_upstream_name] proxy_alternative_upstream_name: [$proxy_alternative_upstream_name] upstream_addr: $upstream_addr upstream_response_length: $upstream_response_length upstream_response_time: $upstream_response_time upstream_status: $upstream_status req_id: $req_id canary: $http_canary'

# helm upgrade --install --atomic ingress-nginx ingress-nginx/ingress-nginx --namespace ingress-nginx --create-namespace --values values.yaml