---
kraft:
  enabled: true

replicaCount: 1

controller:
  replicaCount: 1

listeners:
  client:
    protocol: PLAINTEXT
  controller:
    protocol: PLAINTEXT

storage:
  size: 10Gi

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 256Mi

# helm upgrade --install --atomic kafka bitnami/kafka --namespace kafka --create-namespace --values values.yaml