---
primary:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

# helm upgrade --install --atomic --create-namespace --namespace postgres --version 16.7.4 --values values.yaml postgres oci://registry-1.docker.io/bitnamicharts/postgresql 