---
primary:
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      memory: 512Mi

# helm upgrade --install --atomic postgres oci://registry-1.docker.io/bitnamicharts/postgresql --namespace postgres --create-namespace --values values.yaml